include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-AsTC

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-br-enum-country-fn-947b70be-a6ab-40c5-9c85-bdc615477fe5
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-AsTC
  environment:
    name: onb-br-enum-country-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-05T13:17:40Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-br-enum-country-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-br-enum-country-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-br-enum-country-fn-947b70be-a6ab-40c5-9c85-bdc615477fe5
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
