apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: b321a65c-2305-408b-bd3a-53260b154604
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-country
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/country
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/country
